version: "3.3"

services:
  loadbalancing:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx-loadbalancing.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${DOCKER_BACKEND_PORT:-8300}:8300"
    depends_on:
      - api

  api:
    build: .
    restart: always
    volumes:
      - ./static:/static
      - .:/code
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CELERY_DATABASE=${REDIS_CELERY_DATABASE}
    depends_on:
      - db
      - cache

  cache:
    image: redis:alpine
    restart: always
    volumes: 
      - ./data/cache:/data

  db:
    image: postgres:14
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - ./../pgAdmin:/pgAdmin
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    profiles:
      - debug
