name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        redis-version: ['latest']

    env:
      DB_PORT: 5432
      DB_NAME: lcm
      DB_USER: openpg
      DB_PASSWORD: openpgpwd

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis:${{ matrix.redis-version }}
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          ENVIRONMENT: testing
          DB_ENGINE: django.db.backends.postgresql
          DB_HOST: 127.0.0.1
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: |
          psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 'OK' AS status;"
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py check
          python3 manage.py loaddata catalog
          python manage.py test
