# Generated by Django 3.2.13 on 2022-10-04 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('lead_title', models.CharField(max_length=128)),
                ('street_address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=16)),
                ('proposal_status', models.CharField(choices=[('approved', 'Approved'), ('release', 'Release'), ('unreleased', 'Unreleased')], default='approved', max_length=16)),
                ('zip_code', models.CharField(max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('confidence', models.IntegerField(default=0)),
                ('estimate_revenue_from', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('estimate_revenue_to', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('projected_sale_date', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=128)),
                ('tags', models.CharField(blank=True, max_length=128)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
