# Generated by Django 3.2.13 on 2022-10-05 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_squashed_0003_alter_leaddetail_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=6)),
                ('email', models.EmailField(max_length=128)),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='partner_image')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadpartner_user_create', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadpartner_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_partner',
            },
        ),
        migrations.CreateModel(
            name='PhoneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'phone_categories',
            },
        ),
        migrations.AddField(
            model_name='leaddetail',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='leaddetail',
            name='state',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='leaddetail',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaddetail_user_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaddetail',
            name='user_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaddetail_user_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='leaddetail',
            table='lead_detail',
        ),
        migrations.CreateModel(
            name='PhoneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('text_massage_received', models.BooleanField(default=False)),
                ('mobile_phone_service_provider', models.CharField(max_length=32)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_phones', to='sales.leadpartner')),
                ('phone_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sales.phonecategory')),
            ],
            options={
                'db_table': 'phone_contact',
            },
        ),
    ]
