# Generated by Django 3.2.13 on 2022-10-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20221005_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddetail',
            name='partner',
            field=models.ManyToManyField(to='sales.LeadPartner'),
        ),
    ]
